### PR TITLE
fix: balance columns

### LINKED ISSUE #28: CSS Columns doesn't work in Firefox

### PR DESCRIPTION
**Pull request by szdc**
This fixes #28 - you already have media queries to change the number of columns as the viewport width changes, so use the default `column-fill` value of `balance` so columns work in Firefox as expected.

### CODE REVIEW

**Comment by singuerinc** [comment]
@szdc, this issue was already fixed in #30 - Thanks for your time though!

**Comment by szdc** [comment]
@singuerinc you merged a fix that changed the property to a vendor-prefixed one, yet the `column-fill` property is [supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/column-fill#Browser_compatibility)? Looks like a hack to me - `column-fill` is now `auto` in Chrome and `balance` in Firefox.

**Comment by singuerinc** [comment]
@szdc I don't really know how the property works. I just tested in both browsers and saw that is working. If you think your approach is better, I can merge your PR.

**Comment by singuerinc** [comment]
@szdc Great!, fixed some conflicts. Seems to work. Thanks!

**Pull request merged**
